services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - .:/app
      - ./meshcentral-data:/app/meshcentral-data
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      HOSTNAME: ${HOSTNAME}
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED:-1}
    restart: unless-stopped 